[package]
name = "FFcodex"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "ffcodex_lib"
crate-type = ["staticlib", "cdylib", "rlib"]


[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
byteorder = "1.5.0"
chromaprint = "0.2.0"
claxon = "0.4.3"
cmake = "0.1.50"
flacenc = "0.4.0"
# lame = "0.1.3"
memmap2 = "0.9.5"
metaflac = "0.2.8"
# minimp3 = "0.5.1"
rayon = "1.10.0"
sha2 = "0.10.9"


[build-dependencies]
cc = "1.2.21"
cmake = "0.1.50"

